# Generated by Django 4.2.6 on 2025-02-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
